import React from "react";
import Navbar from "./components/Navbar.jsx"
import './App.css'

export default function App() {
  return (
    <div>
      <Navbar />
      <ul>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
        <li>ahhhhhhhhhhh</li>
      </ul>
      <h1 id="scroll">test</h1>
    </div>
  )
}